- id: Cleaning_rooms
  alias: Start Cleaning Room
  trigger:
  - platform: state
    entity_id: input_select.vacuum_room
    from: Wybierz pomeszczenie
  action:
  - service: script.turn_on
    data_template:
      entity_id: "{% if is_state(\"input_select.vacuum_room\", \"salon\") %}\n  script.vacuum_salon\n\
        {% elif is_state(\"input_select.vacuum_room\", \"kuchnia\") %}\n  script.vacuum_kuchnia\n\
        {% elif is_state(\"input_select.vacuum_room\", \"przedpokój\") %}\n  script.vacuum_przedpokoj\n\
        {% elif is_state(\"input_select.vacuum_room\", \"łazienka\") %}\n  script.vacuum_lazienka\n\
        {% elif is_state(\"input_select.vacuum_room\", \"pokój dzieci\") %}\n  script.vacuum_pokojdzieci\n\
        {% else %} {% endif %}\n"
  - service: input_select.select_option
    entity_id: input_select.vacuum_room
    data_template:
      option: Select
- id: vacuum_water_grade_switch
  alias: Ilosc wody
  trigger:
  - entity_id: vacuum.darek
    platform: state
  action:
  - service_template: "{% if states.vacuum.darek.attributes.water_grade == 11  %}\n\
      \  script.vacuum_water_grade_medium\n{% elif states.vacuum.darek.attributes.water_grade\
      \ == 12  %}\n  script.vacuum_water_grade_high\n{% elif states.vacuum.darek.attributes.water_grade\
      \ == 13  %}\n  script.vacuum_water_grade_low\n{% else %} {% endif %}\n"
  - data: {}
    entity_id: automation.ilosc_wody
    service: automation.turn_off
  initial_state: false
- id: vacuum_fan_speed
  alias: tryb odkurzania
  trigger:
  - entity_id: vacuum.darek
    platform: state
  action:
  - service_template: "{% if states.vacuum.darek.attributes.suction_grade == 0  %}\n\
      \  script.vacuum_set_standard\n{% elif states.vacuum.darek.attributes.suction_grade\
      \ == 1  %}\n  script.vacuum_set_medium\n{% elif states.vacuum.darek.attributes.suction_grade\
      \ == 2  %}\n  script.vacuum_set_turbo\n{% elif states.vacuum.darek.attributes.suction_grade\
      \ == 3  %}\n  script.vacuum_set_silente\n{% else %}\nscript.vacuum_set_silente\n\
      {% endif %}\n"
  - data: {}
    entity_id: automation.tryb_odkurzania
    service: automation.turn_off
  initial_state: false
- id: vacuum_led_switch
  alias: led status
  trigger:
  - entity_id: vacuum.darek
    platform: state
  action:
  - service_template: "{% if states.vacuum.darek.attributes.repeat_state == 0  %}\n\
      \  script.vacuum_set_light_on\n{% elif states.vacuum.darek.attributes.repeat_state\
      \ == 1  %}\n  script.vacuum_set_light_off\n{% else %}{% endif %}\n"
  - data: {}
    entity_id: automation.led_status
    service: automation.turn_off
  initial_state: false
- id: vacuum_set_mop
  alias: tryb pracy
  trigger:
  - entity_id: vacuum.darek
    platform: state
  action:
  - service_template: "{% if states.vacuum.darek.attributes.is_mop == 0  %}\n  script.vacuum_set_mop_1\n\
      {% elif states.vacuum.darek.attributes.is_mop == 1  %}\n  script.vacuum_set_mop_2\n\
      {% else %}\nscript.vacuum_set_mop_0\n{% endif %}\n"
  - data: {}
    entity_id: automation.tryb_pracy
    service: automation.turn_off
  initial_state: false
