- id: '1582326084303'
  alias: Nocna on
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.master_1_2
    state: 'off'
  - condition: or
    conditions:
    - condition: state
      entity_id: switch.master_2
      state: 'off'
  action:
  - entity_id: light.night_lamp
    service: light.turn_on
- id: '1582326837457'
  alias: Nocna off
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    for: 00:00:15
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: light.night_lamp
    service: light.turn_off
- id: '1582326975988'
  alias: Remote Nocna
  description: ''
  trigger:
  - device_id: 380f32b4c8254e86b17ded521e964b75
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - entity_id: light.night_lamp
    service: light.toggle
- id: '1582327081057'
  alias: Remote Nocna max
  description: ''
  trigger:
  - device_id: 380f32b4c8254e86b17ded521e964b75
    domain: deconz
    platform: device
    subtype: dim_up
    type: remote_button_long_press
  condition: []
  action:
  - entity_id: scene.dim_max_up
    service: scene.turn_on
- id: '1582327145718'
  alias: Renote Nocna mini
  description: ''
  trigger:
  - device_id: 380f32b4c8254e86b17ded521e964b75
    domain: deconz
    platform: device
    subtype: dim_down
    type: remote_button_long_press
  condition: []
  action:
  - entity_id: scene.dim_minimum_down
    service: scene.turn_on
- id: '1582354689145'
  alias: Dzien
  description: ''
  trigger:
  - event: sunrise
    offset: 00:45:00
    platform: sun
  condition: []
  action:
  - entity_id: automation.nocna_on
    service: automation.turn_off
- id: '1582354770076'
  alias: Noc
  description: ''
  trigger:
  - event: sunset
    offset: -00:15:00
    platform: sun
  condition: []
  action:
  - entity_id: automation.nocna_on
    service: automation.turn_on
  - entity_id: input_boolean.lili_wstala
    service: input_boolean.turn_off
- id: '1582354962792'
  alias: Lili watala
  description: ''
  trigger:
  - entity_id: binary_sensor.motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.lili_wstala
    state: 'off'
  - after: 06:30:00
    before: '10:30:00'
    condition: time
  action:
  - entity_id: input_boolean.lili_wstala
    service: input_boolean.turn_on
  - service: script.1582355098009
- id: '1582481838378'
  alias: Master on - Nocna off
  description: ''
  trigger:
  - entity_id: switch.master_1_2
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: switch.master_2
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: light.reading_light
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: light.night_lamp
    service: light.turn_off
- id: '1583514839789'
  alias: Okno
  description: ''
  trigger:
  - device_id: 40f6f6ab46784155aa31249ff77ac026
    domain: binary_sensor
    entity_id: binary_sensor.window_door_sensor
    for:
      hours: 0
      minutes: 10
      seconds: 0
    platform: device
    type: opened
  condition:
  - after: '18:00'
    before: '21:00'
    condition: time
  action:
  - data: {}
    service: script.1583500938869
- id: Cleaning_rooms
  alias: Start Cleaning Room
  trigger:
  - platform: state
    entity_id: input_select.vacuum_room
    from: Wybierz pomeszczenie
  action:
  - service: script.turn_on
    data_template:
      entity_id: "{% if is_state(\"input_select.vacuum_room\", \"salon\") %}\n  script.vacuum_salon\n\
        {% elif is_state(\"input_select.vacuum_room\", \"kuchnia\") %}\n  script.vacuum_kuchnia\n\
        {% elif is_state(\"input_select.vacuum_room\", \"przedpokój\") %}\n  script.vacuum_przedpokoj\n\
        {% elif is_state(\"input_select.vacuum_room\", \"łazienka\") %}\n  script.vacuum_lazienka\n\
        {% elif is_state(\"input_select.vacuum_room\", \"pokój dzieci\") %}\n  script.vacuum_pokojdzieci\n\
        {% else %} {% endif %}\n"
  - service: input_select.select_option
    entity_id: input_select.vacuum_room
    data_template:
      option: Select
- id: vacuum_water_grade_switch
  alias: Ilosc wody
  trigger:
  - entity_id: vacuum.darek
    platform: state
  action:
  - service_template: "{% if states.vacuum.darek.attributes.water_grade == 11  %}\n\
      \  script.vacuum_water_grade_medium\n{% elif states.vacuum.darek.attributes.water_grade\
      \ == 12  %}\n  script.vacuum_water_grade_high\n{% elif states.vacuum.darek.attributes.water_grade\
      \ == 13  %}\n  script.vacuum_water_grade_low\n{% else %} {% endif %}\n"
  - data: {}
    entity_id: automation.ilosc_wody
    service: automation.turn_off
  initial_state: false
- id: vacuum_fan_speed
  alias: tryb odkurzania
  trigger:
  - entity_id: vacuum.darek
    platform: state
  action:
  - service_template: "{% if states.vacuum.darek.attributes.suction_grade == 0  %}\n\
      \  script.vacuum_set_standard\n{% elif states.vacuum.darek.attributes.suction_grade\
      \ == 1  %}\n  script.vacuum_set_medium\n{% elif states.vacuum.darek.attributes.suction_grade\
      \ == 2  %}\n  script.vacuum_set_turbo\n{% elif states.vacuum.darek.attributes.suction_grade\
      \ == 3  %}\n  script.vacuum_set_silente\n{% else %}\nscript.vacuum_set_silente\n\
      {% endif %}\n"
  - data: {}
    entity_id: automation.tryb_odkurzania
    service: automation.turn_off
  initial_state: false
- id: vacuum_led_switch
  alias: led status
  trigger:
  - entity_id: vacuum.darek
    platform: state
  action:
  - service_template: "{% if states.vacuum.darek.attributes.repeat_state == 0  %}\n\
      \  script.vacuum_set_light_on\n{% elif states.vacuum.darek.attributes.repeat_state\
      \ == 1  %}\n  script.vacuum_set_light_off\n{% else %}{% endif %}\n"
  - data: {}
    entity_id: automation.led_status
    service: automation.turn_off
  initial_state: false
- id: vacuum_set_mop
  alias: tryb pracy
  trigger:
  - entity_id: vacuum.darek
    platform: state
  action:
  - service_template: "{% if states.vacuum.darek.attributes.is_mop == 0  %}\n  script.vacuum_set_mop_1\n\
      {% elif states.vacuum.darek.attributes.is_mop == 1  %}\n  script.vacuum_set_mop_2\n\
      {% else %}\nscript.vacuum_set_mop_0\n{% endif %}\n"
  - data: {}
    entity_id: automation.tryb_pracy
    service: automation.turn_off
  initial_state: false
- id: '1586781724610'
  alias: glosnosc w dol
  description: ''
  trigger:
  - device_id: 380f32b4c8254e86b17ded521e964b75
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: media_player.bedroom
    service: media_player.volume_down
- id: '1586781891146'
  alias: glosnosc góra
  description: ''
  trigger:
  - device_id: 380f32b4c8254e86b17ded521e964b75
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: media_player.bedroom
    service: media_player.volume_up
- id: '1587705358552'
  alias: test obecnosc wyjscie
  description: ''
  trigger:
  - device_id: 90468d40b99c43248893f1587e929c86
    domain: binary_sensor
    entity_id: binary_sensor.opaska_miband4
    platform: device
    type: turned_off
  condition: []
  action:
  - data:
      message: opaska opuscila dom
      title: opaska
    service: notify.mobile_app_lenovo_k53a48
- id: '1587705456915'
  alias: obecnosc opaska przybycie
  description: ''
  trigger:
  - device_id: 90468d40b99c43248893f1587e929c86
    domain: binary_sensor
    entity_id: binary_sensor.opaska_miband4
    platform: device
    type: turned_on
  condition: []
  action:
  - data:
      message: opaska w domu
      title: dom
    service: notify.mobile_app_lenovo_k53a48
