vacuum: !include vacuum.yaml

input_select:
  vacuum_room:
    name: Które pomieszczenie odkurzać
    options:
      - Wybierz pomeszczenie
      - sypialnia
      - salon
      - kuchnia
      - przedpokój
      - łazienka
      - pokój dzieci
