
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

homeassistant:
 customize: !include customize.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
zone: !include zone.yaml
scene: !include scenes.yaml
climate: !include climate.yaml
vacuum: !include vacuum.yaml
#template: !include template.yaml
#switch: !include switch.yaml
#device_tracker: !include device_tracker.yaml
frontend:
  themes: !include_dir_merge_named themes
  
recorder:
  db_url: !secret maria

cloud:
alexa_media:
  accounts:
    - email: d@gmail.com
      password: !secret amazon_password
      url: amazon.com

input_boolean:
  lili_wstala:
    name: Lili wstala

input_select:
  vacuum_room:
    name: Które pomieszczenie odkurzać
    options:
      - Wybierz pomeszczenie
      - sypialnia
      - salon
      - kuchnia
      - przedpokój
      - łazienka
      - pokój dzieci

shopping_list:

logger:
  default: info
  logs:
    hacs: debug
    miio2: debug

#discovery:
#  ignore:
#   - yeelight
yeelight:
  devices:
   192.168.1.12:
    name: night lamp


# Example configuration.yaml entry
#mysensors:
#  gateways:
#    - device: '/dev/ttyUSB0'
#  persistence: false
#      persistence_file: '/config/mysensors_433.json'
#      baud_rate: 38400
#  optimistic: false
#  persistence: true
#  retain: true
#  version: 2.2

sonoff:
  username: d@gmail.com 
  password: !secret sonoff
  scan_interval: 60 #(optional)
  grace_period: 600 #(optional)
  api_region: 'eu' #polecam dodać
  entity_prefix: True #usuwa prefix sonoff z nazw urządzeń
  debug: False #(optional)

########################










